### ISSUE TITLE
Activity yaml should be 1 based, not 0 based

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#616]
The yaml being submitted currently contains
```
activity:
- 0:
  - repo: name
  - link: URL
  - details: shortlog
```

It should be either 1 based, or be an array like

activity:
  - repo: name
    link: URL
    details: shortlog
  - repo: name2
    link: URL2
    details: shortlog2
```
